#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80

# Update the package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the default Nginx configuration file
sudo cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # Add the "Holberton School" string to the response
        add_header X-Holberton "Holberton School";
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx manually (without using systemctl)
sudo nginx -s reload
