#!/usr/bin/env bash
# Update the package index

sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the default index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure the Nginx redirect
sudo bash -c 'cat << EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

sudo service nginx restart
